### ISSUE TITLE
Quickstart docs for jQuery not available

### ISSUE THREAD

**Issue by gidsey** [tapmodo/Jcrop#297]
Hi,

Just started using Jcrop and noticed that the page for jQuery quickstart docs on your site seems to be down: https://jcrop.com/jquery/

Thanks,
Chris

**Comment by zwantE** [comment]
push

**Comment by KunwarSagar** [comment]
https://web.archive.org/web/20130504111828/http://deepliquid.com/content/Jcrop_API.html

**Comment by manchumahara** [comment]
@KunwarSagar  does it work with latest version ?

**Comment by sunco007** [comment]
Jcrop not working with me using Jquery 3.7.1. I just got Uncaught TypeError: $(...).Jcrop is not a function

It autompletes in the console

Works with Jquery 2.1.3 as I see an example in CodePen.. can't downgrade Jquery
